spring.application.name=sign-language-recognizer
# Path (relative to project root or absolute) to your ONNX model
model.path=models/slr_model.onnx

# Sequencing & feature config ? must match the exported ONNX model input shape
model.sequence.length=30
model.feature.dim=49152
# Labels (comma-separated); match the order used during model training/export
model.labels=Hello,Thank You,Yes,No,Help,I Love You